### ISSUE TITLE
Seat count tracking

### ISSUE THREAD

**Issue by jacksonjude** [UCSB-Schedule-Builder/UCSB-Schedule-Builder#20]
- [ ] Track seat counts over time (every hour/15 mins during pass times) in course database OR separate database
- [ ] Rate a course on competitiveness (also account for instructor)
- [ ] REACH: Calculate probability chance of schedules being available based on course & instructor, and the user's pass times
